services:
  - type: web
    name: affiliatehunter-backend
    runtime: docker
    repo: https://github.com/DEEDS99/affiliatehunter
    branch: main
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  - type: web
    name: affiliatehunter-frontend
    runtime: node
    repo: https://github.com/DEEDS99/affiliatehunter
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
